# Generated by Django 3.2.2 on 2021-05-13 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mName', models.CharField(max_length=64)),
                ('mCode', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.CharField(default=1, max_length=8)),
                ('pType', models.CharField(max_length=1)),
                ('validTime', models.DateField()),
                ('pLocation', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passport', to='citizens.manager')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('code', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='citizens.passport')),
                ('origin', models.CharField(max_length=64)),
                ('originTime', models.DateField()),
                ('destination', models.CharField(max_length=64)),
                ('destinationTime', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('name', models.CharField(max_length=64)),
                ('sex', models.CharField(max_length=1)),
                ('year', models.DateField()),
                ('code', models.BigAutoField(default=None, primary_key=True, serialize=False)),
                ('sID', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='citizens.passport')),
                ('hID', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='citizens.history')),
            ],
        ),
    ]
